### PR TITLE
Split wormwood into modules, add realtime mode, and other improvements.

### PR DESCRIPTION
**Pull request by ZachyCatGames**
This heavily refactors wormwood by splitting it up into several modules with the intent of hiding/abstracting elements which are irrelevant to the assignment, along with other improvements.

Wormwood is now split up into the following modules:
wormwood/main: Interacts with all of the other modules and is what contains the (intentional) vulns/bugs
status: Handles creating and managing the large status window a the top of the screen.
console: Provides the console on the bottom half of the screen. This abstracts away a lot of the ncurses stuff and implements a custom get string/char which can be interrupted (required for realtime mode).
reactor: Contains/hides all of the locking/threading code used for realtime mode and reactor update code that shouldn't be touched.

The other significant change is the addition of a realtime mode, which automatically updates the reactor state every so often (currently 2s) opposed to only having it update when the user performs an action.

This currently fixes:
#3
#5
#6
#7
#8
#9
#10 (may change colors later)
#14
#15
#17 (now only occurs on errors)
#18 (only displays wait option in non-realtime mode)
#19
#20
#21
#23

### CODE REVIEW

**Comment by ZachyCatGames** [comment]
Fixed #14 & #18

**Comment by ZachyCatGames** [comment]
Fixed #20

**Comment by ZachyCatGames** [comment]
Fixed #23

**Comment by pahp** [comment]
@ZachyCatGames - Looks like authenticating as `oper`/`HomerSimpson` does not work?

**Comment by ZachyCatGames** [comment]
Ah, whoops, incorrectly copy-pasted some stuff in https://github.com/pahp/wormwood/pull/22/commits/342253d8dfd6ed84cdfe66c38ece2b4579f5694c

Fixed with https://github.com/pahp/wormwood/pull/22/commits/c740b1ac8cd26927755f5cf3b1d4c3f957bdd06e

**Comment by pahp** [comment]
Thanks for all your hard work!

**Pull request merged**
